apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubechart
  namespace: kubechart
  labels:
    app: kubechart
spec:
  parentRefs:
    - name: platform-gateway
      namespace: envoy-gateway-system
      kind: Gateway
      port: 80
    - name: platform-gateway
      namespace: envoy-gateway-system
      kind: Gateway
      port: 443
  hostnames:
    - "kubechart.example.com"
    - "*.kubechart.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kubechart
          port: 80
          kind: Service
          weight: 100
