apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubechart
  namespace: kubechart
  labels:
    app: kubechart
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kubechart.example.com
      secretName: kubechart-tls
  rules:
    - host: kubechart.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubechart
                port:
                  name: http
