apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubechart
  namespace: kubechart
  labels:
    app: kubechart

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubechart
  namespace: kubechart
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubechart
  namespace: kubechart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubechart
subjects:
  - kind: ServiceAccount
    name: kubechart
    namespace: kubechart
